const randomString = 'xxxx-0000-12345-ABCDE';

const fakeTabsTestCases = {
  signHereTabs: [
    {
      stampType: 'signature',
      name: 'SignHere',
      tabLabel: 'Grantee Representative Signature',
      scaleValue: 1.0,
      optional: 'false',
      documentId: '1',
      recipientId: randomString,
      pageNumber: '7',
      xPosition: '288',
      yPosition: '122',
      tabId: randomString,
      templateLocked: 'false',
      templateRequired: 'false',
      status: 'signed',
    },
  ],
  fullNameTabs: [
    {
      name: 'FullName',
      value: 'Harry Potter',
      tabLabel: randomString,
      fontColor: 'black',
      fontSize: 'size9',
      documentId: '1',
      recipientId: randomString,
      pageNumber: '7',
      xPosition: '70',
      yPosition: '159',
      tabId: randomString,
      templateLocked: 'false',
      templateRequired: 'false',
    },
  ],
  dateSignedTabs: [
    {
      name: 'DateSigned',
      value: '2020-06-22T14:26:12.0000000Z',
      tabLabel: randomString,
      font: 'lucidaconsole',
      fontColor: 'black',
      fontSize: 'size9',
      documentId: '1',
      recipientId: randomString,
      pageNumber: '7',
      xPosition: '463',
      yPosition: '158',
      tabId: randomString,
      templateLocked: 'false',
      templateRequired: 'false',
    },
  ],
  textTabs: [
    {
      height: 11,
      validationPattern: '',
      validationMessage: '',
      shared: 'false',
      requireInitialOnSharedChange: 'false',
      requireAll: 'false',
      value: 'Oregon State University',
      originalValue: 'Oregon State University',
      width: 180,
      required: 'true',
      locked: 'true',
      concealValueOnDocument: 'false',
      disableAutoSize: 'false',
      maxLength: 4000,
      tabLabel: randomString,
      font: 'lucidaconsole',
      fontColor: 'black',
      fontSize: 'size9',
      documentId: '1',
      recipientId: randomString,
      pageNumber: '1',
      xPosition: '217',
      yPosition: '291',
      tabId: randomString,
      templateLocked: 'false',
      templateRequired: 'false',
    },
  ],
  numberTabs: [
    {
      validationPattern: '',
      validationMessage: '',
      shared: 'false',
      requireInitialOnSharedChange: 'false',
      requireAll: 'false',
      name: 'Estimated Total Amount of Training in Academic Years:',
      value: '2',
      width: 162,
      required: 'true',
      locked: 'false',
      concealValueOnDocument: 'false',
      disableAutoSize: 'false',
      maxLength: 4000,
      tabLabel: 'Estimated Total Amount of Training in Academic Years',
      font: 'helvetica',
      fontColor: 'black',
      fontSize: 'size9',
      documentId: '1',
      recipientId: randomString,
      pageNumber: '4',
      xPosition: '365',
      yPosition: '191',
      tabId: randomString,
      templateLocked: 'false',
      templateRequired: 'false',
    },
  ],
  ssnTabs: [
    {
      validationPattern: '',
      validationMessage: '',
      shared: 'false',
      requireInitialOnSharedChange: 'false',
      requireAll: 'false',
      name: 'Social Security Number*:',
      value: '123-45-6789',
      width: 120,
      required: 'true',
      locked: 'false',
      concealValueOnDocument: 'false',
      disableAutoSize: 'false',
      maxLength: 4000,
      tabLabel: 'Social Security Number',
      font: 'helvetica',
      fontColor: 'black',
      fontSize: 'size9',
      documentId: '1',
      recipientId: randomString,
      pageNumber: '4',
      xPosition: '216',
      yPosition: '335',
      tabId: randomString,
      templateLocked: 'false',
      templateRequired: 'false',
    },
  ],
  dateTabs: [
    {
      validationPattern: '^(|by DocuSign)((|0)[1-9]|1[0-2])/((|0)[1-9]|[1-2][0-9]|3[0-1])/[0-9]{4}$',
      validationMessage: 'Enter date with format MM/DD/YYYY ',
      shared: 'false',
      requireInitialOnSharedChange: 'false',
      requireAll: 'false',
      name: 'Text 25',
      value: '10/08/1957',
      width: 120,
      required: 'true',
      locked: 'false',
      concealValueOnDocument: 'false',
      disableAutoSize: 'false',
      maxLength: 4000,
      tabLabel: 'Date of Scholarship Assistance and Service Obligation Meeting',
      font: 'helvetica',
      fontColor: 'black',
      fontSize: 'size9',
      documentId: '1',
      recipientId: randomString,
      pageNumber: '4',
      xPosition: '405',
      yPosition: '176',
      tabId: randomString,
      templateLocked: 'false',
      templateRequired: 'false',
    },
  ],
  emailTabs: [
    {
      validationPattern: '',
      validationMessage: '',
      shared: 'false',
      requireInitialOnSharedChange: 'false',
      requireAll: 'false',
      name: 'Alternative E-mail Address:',
      value: 'asdfasdf@asdfasdf.edu',
      width: 318,
      required: 'true',
      locked: 'false',
      concealValueOnDocument: 'false',
      disableAutoSize: 'false',
      maxLength: 4000,
      tabLabel: 'Alternative Email Address',
      font: 'helvetica',
      fontColor: 'black',
      fontSize: 'size9',
      documentId: '1',
      recipientId: randomString,
      pageNumber: '4',
      xPosition: '228',
      yPosition: '408',
      tabId: randomString,
      templateLocked: 'false',
      templateRequired: 'false',
    },
  ],
};

module.exports = { fakeTabsTestCases };
